-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Autobuses"
(
    id serial,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Conductores"
(
    id serial,
    nombre character varying,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Lugares"
(
    id serial,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Autobuses_Lugares"
(
    "Autobuses_id" serial,
    "Lugares_id" serial,
    "Conductores_id" serial,
    fecha date,
    PRIMARY KEY (fecha)
);

ALTER TABLE IF EXISTS public."Autobuses_Lugares"
    ADD FOREIGN KEY ("Autobuses_id")
    REFERENCES public."Autobuses" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Autobuses_Lugares"
    ADD FOREIGN KEY ("Lugares_id")
    REFERENCES public."Lugares" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Autobuses_Lugares"
    ADD FOREIGN KEY ("Conductores_id")
    REFERENCES public."Conductores" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;